spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&userSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  #order端口号
  port: 8081
env:
  test5
